### PR TITLE
Patch command injection vulnerability

### PR DESCRIPTION
**Pull request by ron-checkmarx**
I made the necessary changes to use `execFile` and `execFileSync` instead of `exec` and `execSync` and also added a test to avoid regression.

closes: #64

### CODE REVIEW

**Review by domharrington — APPROVED** [review]
This looks great to me, thanks so much for submitting! @hipstersmoothie you happy with this and can you publish if so?

**Review by hipstersmoothie — APPROVED** [review]

**Comment by ron-checkmarx** [comment]
@hipstersmoothie apologies for the multiple messages about this, but I will really appreciate you publishing the changes to npm.

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in [`v4.0.4`](https://github.com/domharrington/node-gitlog/releases/tag/v4.0.4) :rocket:

**Comment by hipstersmoothie** [comment]
Sorry CI was failing but got the release out!

**Pull request merged**
