### PR TITLE
Used child process/spawn rather then exec to fix maxBuffer bug

### PR DESCRIPTION
**Pull request by atmd83**
Hi,

Re: [https://github.com/domharrington/node-gitlog/issues/16](https://github.com/domharrington/node-gitlog/issues/16) ,this PR uses spawn/child process rather then exec() to fix the max buffer bug on that issue.

most of the code is the same except the args are built as an array rather than concat'ing a string.

All tests pass

Andrew

### CODE REVIEW

**Comment by atmd83** [comment]
The tests are failing and jshint it showing errors. is there a different .jshintrc used on the CI?

Error is that Promise is not defined, but this has been added to the .jshintrc file. 
Are pull request ran on the CI directly or using some sort of config? I'm not seeing errors/failing tests locally

**Comment by atmd83** [comment]
Closed this. Doesn't need to use promises

**Comment by domharrington** [comment]
@atmd83 did you still want this merged?

**Comment by atmd83** [comment]
Hi,  I created https://github.com/domharrington/node-gitlog/pull/18 once I'd closed this as I was using promises which didnt need to happen, however although the code on https://github.com/domharrington/node-gitlog/pull/18 works fine, it's not got 100% coverage and failed the CI. https://github.com/domharrington/node-gitlog/pull/18 is the better fix.

**Pull request closed without merging**
