### PR TITLE
Omit files from git log when not configured

### PR DESCRIPTION
**Pull request by palortoff**

### CODE REVIEW

**Comment by domharrington** [comment]
What is the purpose of this? Is this a breaking change? I'm not too familiar with what the `--name-status` option does.

**Comment by palortoff** [comment]
It's not breaking.

the ``--name-status`` flag in ``git log`` appends the status and path of all the files changed in each commit.

When searching in a large repository with many commits, changing lots of files the console output can get very long and result in a ``[Error: stdout maxBuffer exceeded.]`` loading stdout into node.

With ``options.nameStatus === false`` the name and status are ignored in ``parseCommit()``. Therefore not grabbing the name and status from git has no ill effect.

**Comment by domharrington** [comment]
I see. So currently it is passing through the `--name-status` argument regardless of whether it is being used or not. Looks like we're now getting a cyclomatic complexity warning from CI, can you take a look at that?

Happy to merge once strider is passing. Thanks!

**Comment by palortoff** [comment]
@domharrington 
All tests are passing now. 

Thanks for the fast response time!

**Comment by domharrington** [comment]
Released as v2.1.2. Thanks!

**Pull request merged**
