### PR TITLE
feat(git parameters): Manage new parameters ('since', 'after', 'until', ...

### PR DESCRIPTION
**Pull request by malys**
I add some new features.

I'm working on Windows and I had problems to be jshint compliant that why I pushed without respect your jshint rules.

If you are interested, you can accept the pull request and generate a new release.

Thanks for you job.

### CODE REVIEW

**Comment by domharrington** [comment]
Hey thanks for your contribution, it is much appreciated. Could you please summarise the changes that you have made? Possibly with an update to the README with usage instructions?

How come you can't be compliant to the jshint setup in this repo? What IDE are you using?

Regards

**Comment by malys** [comment]
Tomorrow,I will update the Readme.md.
I use webstorm and brackets. Your formatting template isn't compatible with JSHint rules.
Moreover, you have specified LF like separator.

**Comment by malys** [comment]
I have updated Readme.md and  added new option changeStatus.

**Comment by domharrington** [comment]
Can you add unit tests for your new functionality? https://github.com/domharrington/node-gitlog/blob/master/test/gitlog.test.js. Tests can be run using `mocha -r should` if you're ignoring the JSHint config.

Regards

**Comment by malys** [comment]
I have lot of issue with your project on windows.
Your tests don't pass. 
On C9,I have rewritten them and I have added new tests.

What IDE are you using?

**Comment by domharrington** [comment]
I'm on OS X 10.10.2, using Sublime Text 3. Tests pass fine on my machine in addition to passing correctly on Travis https://travis-ci.org/domharrington/node-gitlog/builds/57769948.

**Comment by domharrington** [comment]
Just realised, it isn't JSHint that your code is failing on, it is `jscs`. Looks like it can be added as a webstorm package: https://www.jetbrains.com/webstorm/help/jscs.html

**Comment by malys** [comment]
I have installed sublimetext with jscs formatter and I fix jscs issue.
Mocha tests don't work on windows. 
I fix them on Cloud9 and I fix parsing issue.
Thanks for your help.

**Comment by malys** [comment]
I have enabled 'nameStatus' option by default. What do you think about this choice?

**Comment by domharrington** [comment]
What is your rationale for wanting to have nameStatus on by default? I think i would consider that a breaking change and would require a major version bump. I'm happy to do this would just like to know why it is so important to you.

**Comment by domharrington** [comment]
I've tidied up some of your code and added to a new pull request #8. Does this look okay?

**Comment by malys** [comment]
It looks okay.

Concerning defaultStatus, It isn't so important but to my mind, it's very interesting to have changed files list by default. Consequently, You can understand easily what is the impact of your commit on the project.

I ask you the question because It's more a strategy to define than a requirement.

**Comment by domharrington** [comment]
Sure thing. I'm happy to add it as a default, i dont have a particular preference either way but i can see the benefit.

**Comment by domharrington** [comment]
Published as v2.0.0. Thanks for your contribution! What are you using this module for btw? Building anything cool?

**Comment by malys** [comment]
Thank you. Cool not really. Unfortunately, I can't spend too much time on this project.

I have created a module to monitor GIT log. The user create rules and the system send alert.

Developers don't need to create merge request but the module detects suspicious commits. We save time for no strategic project.

Thank you for your help. It really was great working with you.

**Comment by domharrington** [comment]
Great stuff, sounds interesting. Is it open source? 

Anytime, thanks for your contribution.

**Comment by malys** [comment]
I will try  to convert this internal project to an open source project. ;)
Bye

**Pull request merged**
