### PR TITLE
Add support for getting commits of line range

### LINKED ISSUE #60: No support for line range
I'd like to be able to look up the log history for a specific line of a file, or a range of lines in a file

### PR DESCRIPTION
**Pull request by SalmonMode**
Closes #60 

I had to tweak a variable name because TS was complaining. Also several tests are failing, but I don't think it's because of what I did.

### CODE REVIEW

**Comment by hipstersmoothie** [comment]
Could you rebase? I reverted the PR that broke all the tests

**Comment by SalmonMode** [comment]
@hipstersmoothie Thanks! I rebased, added a test, and also modified a few of the tests a little bit just to speed the tests up a little (they were all calling `gitlog` the same way, and none modify the results, so it's safe).

**Comment by hipstersmoothie** [comment]
Awesome! Running the tests locally though it looks like one of them doesn't pass

```
 ✕ returns C100 status for files that are copied (1535ms)
```

**Comment by SalmonMode** [comment]
hmmmm it's passing for me. I also ran the create repo script and ran the commands myself, and it seems to be working.

The command it came up with for that one was this for me:

```
git log --find-copies-harder -n 10 --pretty="@begin@        %h      %H      %s      %an     %ai@end@" --name-status
```

I also confirmed with a similar test (`returns A status for files that are added`), which produces this command

```
git log -n 10 --pretty="@begin@     %h      %H      %s      %an     %ai@end@" --name-status
```

and when I ran that myself, I saw the `A` in place of the `C100` from the previous test's command.

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in [`v4.0.2`](https://github.com/domharrington/node-gitlog/releases/tag/v4.0.2) :rocket:

**Pull request merged**
